apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdemo1-deployment
  labels:
    app: appdemo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdemo1
  template:
    metadata:
      labels:
        app: appdemo1
    spec:
      containers:
        - name: appdemo1 
          image: appdemo1acs.azurecr.io/myprojectappdemo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:   # Update Image Pull Secret Name we creted
        - name: appdemo-secret  
---
apiVersion: v1
kind: Service
metadata:
  name: appdemo1-loadbalancer-service
  labels:
    app: appdemo1
spec:
  type: LoadBalancer
  selector:
    app: appdemo1
  ports:
    - port: 80
      targetPort: 80
        
