apiVersion : apps/v1
kind: Deployment
metadata:
  name: appdemo1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdemo1
  template:
    metadata:
      labels:
        app: appdemo1 
    spec:
      containers:
        - name: appdemo1 
          image: appdemo1acr.azurecr.io/appdemo1
          ports:
          - containerPort: 80